web/Models/Message.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations.Schema;


namespace web.Models
{
    [Table("Message", Schema = "dbo")]
    public class Message
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Context { get; set; }
        public DateTime CreatDate { get; set; }
    }
}

web/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Library;
using System.Web.Mvc;
using web.Data;
using System.Data.Entity;
using System.Text;
using System.Threading.Tasks;
using Message = web.Models.Message;

namespace webtext.web.Controllers
{
    public class MessageController : Controller
    {
        public ActionResult Index()
        {
            MessageWeb messageWeb = new MessageWeb();
            List<Library.Message> messages = messageWeb.Messages.ToList();
            return View(messages);
        }

        public ActionResult Details(int id = 0)
        {
            var WebContext = new webContext();
            Message message;
            if (id == 0)
            {
                message = new Message
                {
                    Id = 0,
                    UserId = 0,
                    UserName = "NULL",
                    Context = "NULL",
                };
            }
            else
            {
                message = WebContext.Messages.Single(p => p.Id == id);
                //Throws exception if can not find the single entity
            }
            return View(message);
        }

        /**建立**/
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Library.Message message)
        {
            if (!ModelState.IsValid)
            {
                return View("Create");
            }

            MessageWeb messageWeb = new MessageWeb();
            messageWeb.AddMessage(message);
            return RedirectToAction("Index");
        }

        /**更新讀取**/
        //[HttpGet]
        //public ActionResult Edit(int id)
        //{
        //    MessageWeb messageWeb = new MessageWeb();
        //    Library.Message message = messageWeb.Messages.Single(g => g.Id == id);
        //    return View(message);
        //}

        ///**更新動作**/
        //[HttpPost]
        //public ActionResult Edit([Bind(Include = "UserId, UserName, Context")]Library.Message message)
        //{
        //    MessageWeb messageWeb = new MessageWeb();
        //    message.Id = messageWeb.Messages.Single(g => g.Id == message.Id).Id;

        //    if (!ModelState.IsValid)
        //    {
        //        return View("Edit", message);
        //    }

        //    messageWeb.SaveMessage(message);

        //    return RedirectToAction("Index");
        //}

        ///**刪除動作**/
        //[HttpPost]
        //public ActionResult Delete(int id)
        //{
        //    MessageWeb messageWeb = new MessageWeb();
        //    messageWeb.DeleteMessage(id);
        //    return RedirectToAction("Index");
        //}

    }
}

web/Controllers/ReplyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Library;
using System.Web.Mvc;
using web.Data;
using System.Data.Entity;
using Reply = web.Models.Reply;


namespace webtext.web.Controllers
{
    public class ReplyController : Controller
    {
        public ActionResult Index()
        {
            ReplyWeb replyWeb = new ReplyWeb();
            List<Library.Reply> replys = replyWeb.Replys.ToList();
            return View(replys);
        }

        public ActionResult Details(int id = 0)
        {
            var WebContext = new webContext();
            Reply reply;
            if (id == 0)
            {
                reply = new Reply
                {
                    Id = 0,
                    UserId = 0,
                    UserName = "NULL",
                    Context = "NULL",
                };
            }
            else
            {
                reply = WebContext.Replys.Single(p => p.Id == id);
                //Throws exception if can not find the single entity
            }
            return View(reply);
        }

        /**建立**/
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Library.Reply reply)
        {
            if (!ModelState.IsValid)
            {
                return View("Create");
            }

            ReplyWeb replyWeb = new ReplyWeb();
            replyWeb.AddReply(reply);
            return RedirectToAction("Index");
        }

    }
}

web/Views/Message/Create.cshtml
@model Library.Message
@{
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<div class="row">
    <h2>新增留言</h2>

    @using (Html.BeginForm("Create", "Message"))
    {
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-horizontal">

            @Html.Hidden("UserId", "2")
            @Html.Hidden("UserName", "BB")

            <div class="form-group">
                @Html.Label("Context", "內容", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextArea("Context", " ", 6, 60, new { style = "border: solid 1px #ccc; border-radius: 0.25rem; " })
                    @Html.ValidationMessageFor(model => model.Context, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="留言" class="btn btn-default  " />
                </div>
            </div>
        </div>
    }
    <div>
        @Html.ActionLink("回到列表", "Index")
    </div>
</div>

web/Views/Message/Index.cshtml
@using Library;
@model IEnumerable<Library.Message>


<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

<div class="row">
    <div class="table-responsive">
        <div class="col-sm-9">
            <button type="button" class="btn btn-primary btn-sm " style="margin-top:10px ;margin-bottom:10px;" value="建立新的留言" onclick="location.href='@Url.Action("Create", "Message")'">建立新的留言</button>
        </div>
        <table class="table">
            <tr>
                <th>
                    @Html.Label("model.Id", "會員編號")
                </th>
                <th>
                    @Html.Label("model.UserId", "會員帳號")
                </th>
                <th>
                    @Html.Label("model.UserName", "會員暱稱")
                </th>
                <th>
                    @Html.Label("model.Context", "留言內容")
                </th>
                <th>
                    @Html.Label("model.CreatDate", "留言日期")
                </th>
                <th></th>
            </tr>

            @foreach (Message item in Model)
            {
                using (Html.BeginForm("Delete", "Message", new { id = item.Id }))
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Id)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.UserId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.UserName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Context)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CreatDate)
                        </td>
                        <td>
                            <input type="button" class="btn btn-primary btn-sm" value="回覆" onclick="location.href='@Url.Action("Create", "Reply")'" />
                            @*<button type="button" class="btn btn-primary btn-sm " style="margin-top:10px ;margin-bottom:10px;" value="建立新的留言" onclick="location.href='@Url.Action("Create", "Message")'">建立新的留言</button>*@
                            <input type="submit" class="btn btn-primary btn-sm" value="刪除" onclick="return confirm('確定要刪除嗎? Id = @item.Id , Name = @item.UserId');" />
                        </td>
                    </tr>
                }
            }
        </table>
    </div>
</div>

@foreach (Message item in Model)
{
    <div class="card">
        <h5 class="card-header">@Html.DisplayFor(modelItem => item.Context)</h5>
        <div class="card-body">
            <h5 class="card-title">@Html.DisplayFor(modelItem => item.UserName)</h5>
            <p class="card-text">@Html.DisplayFor(modelItem => item.Context)</p>
            <input type="button" class="btn btn-primary btn-sm" value="回覆" onclick="location.href='@Url.Action("Create", "Reply")'" />
        </div>
    </div>
}