web/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Library;
using System.Web.Mvc;
using web.Data;
using System.Data.Entity;
using System.Text;
using System.Threading.Tasks;
using Message = web.Models.Message;

namespace webtext.web.Controllers
{
    public class MessageController : Controller
    {
        public ActionResult Index()
        {
            MessageWeb messageWeb = new MessageWeb();
            List<Library.Message> messages = messageWeb.Messages.ToList();
            return View(messages);
        }

        public ActionResult Details(int id = 0)
        {
            var WebContext = new webContext();
            Message message;
            if (id == 0)
            {
                message = new Message
                {
                    Id = 0,
                    UserId = 0,
                    UserName = "NULL",
                    Context = "NULL",
                };
            }
            else
            {
                message = WebContext.Messages.Single(p => p.Id == id);
                //Throws exception if can not find the single entity
            }
            return View(message);
        }

        /**建立**/
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Library.Message message)
        {
            if (!ModelState.IsValid)
            {
                return View("Create");
            }

            MessageWeb messageWeb = new MessageWeb();
            messageWeb.AddMessage(message);
            return RedirectToAction("Index");
        }

        /**更新讀取**/
        //[HttpGet]
        //public ActionResult Edit(int id)
        //{
        //    MessageWeb messageWeb = new MessageWeb();
        //    Library.Message message = messageWeb.Messages.Single(g => g.Id == id);
        //    return View(message);
        //}

        ///**更新動作**/
        //[HttpPost]
        //public ActionResult Edit([Bind(Include = "UserId, UserName, Context")]Library.Message message)
        //{
        //    MessageWeb messageWeb = new MessageWeb();
        //    message.Id = messageWeb.Messages.Single(g => g.Id == message.Id).Id;

        //    if (!ModelState.IsValid)
        //    {
        //        return View("Edit", message);
        //    }

        //    messageWeb.SaveMessage(message);

        //    return RedirectToAction("Index");
        //}

        ///**刪除動作**/
        //[HttpPost]
        //public ActionResult Delete(int id)
        //{
        //    MessageWeb messageWeb = new MessageWeb();
        //    messageWeb.DeleteMessage(id);
        //    return RedirectToAction("Index");
        //}

    }
}

web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Library;
using System.Web.Mvc;
using web.Data;
using System.Data.Entity;
using System.Text;
using System.Threading.Tasks;
using User = web.Models.User;

namespace webtext.web.Controllers
{
    public class UserController : Controller
    {
        public ActionResult Index()
        {
            UserWeb userWeb = new UserWeb();
            List<Library.User> users = userWeb.Users.ToList();
            return View(users);
        }

        public ActionResult Details(int id)
        {
            var WebContext = new webContext();
            User user;
            if (id == 0)
            {
                user = new User
                {
                    Id = 0,
                    UserAccount = "Name0",
                    UserClass = "NULL",
                    Email = "NULL",
                    Password = "NULL",
                    UserName = "NULL"
                };
            }
            else
            {
                user = WebContext.Users.Single(p => p.Id == id);
                //    //UserWeb userWeb = new UserWeb();
                //    //Library.User user = userWeb.Users.Single(g => g.Id == id);

                //    //Throws exception if can not find the single entity
            }
            return View();
        }

        /**建立**/
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Library.User user)
        {
            if (!ModelState.IsValid)
            {
                return View("Create");
            }

            UserWeb userWeb = new UserWeb();
            userWeb.AddUser(user);
            return RedirectToAction("Index");
        }

        /**更新讀取**/
        [HttpGet]
        public ActionResult Edit(int id)
        {
            UserWeb userWeb = new UserWeb();
            Library.User user = userWeb.Users.Single(g => g.Id == id);
            return View(user);
        }

        /**更新動作**/
        [HttpPost]
        public ActionResult Edit([Bind(Include = "UserAccount, UserClass, Email, Password, UserName")]Library.User user)
        {
            UserWeb userWeb = new UserWeb();
            user.Id = userWeb.Users.Single(g => g.Id == user.Id).Id;

            if (!ModelState.IsValid)
            {
                return View("Edit", user);
            }

            userWeb.SaveUser(user);

            return RedirectToAction("Index");
        }

        /**刪除動作**/
        [HttpPost]
        public ActionResult Delete(int id)
        {
            UserWeb userWeb = new UserWeb();
            userWeb.DeleteUser(id);
            return RedirectToAction("Index");
        }


    }
}

web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Anna's Web</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Anna's Web", "Index", "Message", new { area = "" }, new { @class = "navbar-brand" })
               @*<div class="collapse navbar-collapse" id="navbarsExample02">*@
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        @Html.ActionLink("會員", "Index", "User", new { area = "User" }, new { @class = "navbar-brand" })
                        @*<a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>*@
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("留言", "Index", "Message", new { area = "Message" }, new { @class = "navbar-brand" })
                        @*<a class="nav-link" href="#">Link</a>*@
                    </li>
                </ul>
            @*</div>*@

              </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Anna's Web</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>